import { ListeningExercise } from "./types";

export const C1_LISTENING_EXERCISES: ListeningExercise[] = [
  {
    id: "list_conn_01",
    category: "CONNECTED_SPEECH",
    title: "Connected Speech: Weak Forms & Flapping in Inquiries",
    scenario: "An engineering manager asks about the upcoming infrastructure deadline.",
    spokenAudioText: "What are you going to do about the quarterly infrastructure forecast?",
    phoneticTranscription: "/wʌdʒə ɡənə duː əbaʊt ðə kwɔːrtərli ˈɪnfrəstrʌktʃər ˈfɔːrkæst/",
    connectedSpeechFeatures: [
      "Assimilation: 'What are you' -> /wʌdʒə/",
      "Reduction: 'going to' -> 'gonna' /ɡənə/",
      "Flap /t/ in 'quarterly' in American English",
    ],
    targetKeywords: ["what", "going", "quarterly", "infrastructure", "forecast"],
    dimension: "RECALL",
    translationEs: "¿Qué vas a hacer con respecto al pronóstico trimestral de infraestructura?",
    hint: "Listen for the rapid reduction of 'What are you going to' (/wʌdʒə ɡənə/).",
  },
  {
    id: "list_conn_02",
    category: "CONNECTED_SPEECH",
    title: "Elision & C1 Phrasal Verb Linking",
    scenario: "A project lead reflects on a discarded architectural proposal.",
    spokenAudioText: "We should have ruled out that architecture last night without hesitation.",
    phoneticTranscription: "/wi ʃʊdə ruːld aʊt ðæt ˈɑːrkətɛktʃər lɑːs naɪt wɪðaʊt hɛzɪˈteɪʃən/",
    connectedSpeechFeatures: [
      "Weak form: 'should have' -> /ʃʊdə/",
      "Consonant-to-vowel linking: 'ruled out' -> /ruːl daʊt/",
      "Elision of /t/: 'last night' -> /lɑːs naɪt/",
    ],
    targetKeywords: ["should", "have", "ruled", "out", "architecture", "last", "night"],
    dimension: "RECALL",
    translationEs: "Deberíamos haber descartado esa arquitectura anoche sin vacilar.",
    hint: "Note the reduction 'should have' (/ʃʊdə/) and linking 'ruled out' (/ruːldaʊt/).",
  },
  {
    id: "list_dict_01",
    category: "FAST_DICTATION",
    title: "Rapid Executive Speech: Phrasal Verb Bottlenecks",
    scenario: "A Chief Product Officer summarizes the core challenge during a product review.",
    spokenAudioText: "It essentially boils down to whether we can mitigate these compliance bottlenecks before the upcoming security audit.",
    phoneticTranscription: "/ɪt ɪˈsɛnʃəli bɔɪlz daʊn tuː ˈwɛðər wi kən ˈmɪtɪɡeɪt ðiːz kəmˈplaɪəns ˈbɑːtlˌnɛks bɪˈfɔːr ði ˈʌpˌkʌmɪŋ sɪˈkjʊrəti ˈɔːdɪt/",
    connectedSpeechFeatures: [
      "Linking: 'boils down to'",
      "Weak form: 'can' -> /kən/",
      "Reduced vowel: 'compliance' -> /kəmˈplaɪəns/",
    ],
    targetKeywords: ["essentially", "boils", "down", "mitigate", "compliance", "bottlenecks", "audit"],
    dimension: "RECALL",
    translationEs: "Básicamente se reduce a si podemos mitigar estos cuellos de botella de cumplimiento antes de la auditoría de seguridad.",
    hint: "Focus on 'boils down to' and the C1 adjective 'compliance bottlenecks'.",
  },
  {
    id: "list_dict_02",
    category: "FAST_DICTATION",
    title: "Inverted Conditional Decoding",
    scenario: "A lead architect explains why the cloud failover strategy succeeded.",
    spokenAudioText: "Had it not been for their quick intervention, we would not be in a position to scale our database today.",
    phoneticTranscription: "/hæd ɪt nɑːt bɪn fər ðɛr kwɪk ˌɪntərˈvɛnʃən wi wʊd nɑːt bi ɪn ə pəˈzɪʃən tuː skeɪl ˈaʊər ˈdeɪtəbeɪs təˈdeɪ/",
    connectedSpeechFeatures: [
      "Flapped /t/ and linking: 'Had it not been' -> /hædɪtnɑːtbɪn/",
      "Weak preposition: 'for' -> /fər/",
      "Weak article: 'in a' -> /ɪnə/",
    ],
    targetKeywords: ["had", "been", "quick", "intervention", "scale", "database"],
    dimension: "RECALL",
    translationEs: "Si no hubiera sido por su rápida intervención, hoy no estaríamos en posición de escalar nuestra base de datos.",
    hint: "This uses the formal inverted conditional 'Had it not been for...'",
  },
  {
    id: "list_comp_01",
    category: "BOARDROOM_COMPREHENSION",
    title: "Executive Strategic Assessment: AI Implementation",
    scenario: "Listen to the director of engineering evaluating quarterly automated code review pilots.",
    spokenAudioText: "While the initial productivity gains were undeniable, what truly astonished the committee was the sheer reduction in regression defects. Nevertheless, under no circumstances should we accelerate our rollout before addressing our edge-case test coverage.",
    phoneticTranscription: "/waɪl ði ɪˈnɪʃəl ˌproʊdʌkˈtɪvəti ɡeɪnz wɜːr ˌʌndɪˈnaɪəbl wʌt ˈtruːli əˈstɑːnɪʃt ðə kəˈmɪti wʌz ðə ʃɪər rɪˈdʌkʃən ɪn rɪˈɡrɛʃən ˈdiːfɛkts/",
    connectedSpeechFeatures: [
      "Wh-cleft sentence focus: 'what truly astonished the committee was...'",
      "Negative inversion warning: 'under no circumstances should we...'",
    ],
    targetKeywords: ["productivity", "astonished", "regression", "defects", "rollout", "coverage"],
    dimension: "RECOGNITION",
    translationEs: "Aunque las ganancias iniciales de productividad fueron innegables, lo que realmente asombró al comité fue la enorme reducción de defectos de regresión. Sin embargo, bajo ninguna circunstancia debemos acelerar el despliegue antes de abordar la cobertura de pruebas.",
    hint: "Identify the speaker's main surprise and their subsequent cautionary recommendation.",
    comprehensionQuestions: [
      {
        id: "q1",
        question: "What surprised the committee the most about the pilot?",
        options: [
          "The speed of the cloud deployment",
          "The substantial drop in regression defects",
          "The immediate cost savings for the engineering department",
          "The pushback from senior software engineers",
        ],
        correctIndex: 1,
        explanation: "The speaker explicitly states: 'what truly astonished the committee was the sheer reduction in regression defects'.",
      },
      {
        id: "q2",
        question: "What is the speaker's executive recommendation regarding the rollout?",
        options: [
          "Immediately expand the rollout to all departments",
          "Halt the pilot completely due to budget constraints",
          "Do not accelerate deployment until edge-case test coverage is resolved",
          "Replace the existing test suite with manual QA testing",
        ],
        correctIndex: 2,
        explanation: "Using negative inversion, the speaker warns: 'under no circumstances should we accelerate our rollout before addressing our edge-case test coverage'.",
      },
    ],
  },
  {
    id: "list_shad_01",
    category: "SHADOWING_LAB",
    title: "Shadowing Lab: Executive Cadence & Tonic Stress",
    scenario: "Practice cadence, pausing, and emphatic stress alignment with this executive briefing clip.",
    spokenAudioText: "To bridge the gap between our vision and our operational execution, we must prioritize resilience above all else.",
    phoneticTranscription: "/tuː brɪdʒ ðə ɡæp bɪˈtwiːn ˈaʊər ˈvɪʒən ænd ˈaʊər ˌɑːpəˈreɪʃənl ˌɛksɪˈkjuːʃən wi mʌst praɪˈɔːrəˌtaɪz rɪˈzɪljəns əˈbʌv ɔːl ɛls/",
    connectedSpeechFeatures: [
      "Collocation chunking: 'bridge the gap'",
      "Rhythm pause after: '...operational execution,'",
      "Tonic stress peak on: 'RESILIENCE'",
    ],
    targetKeywords: ["bridge", "gap", "vision", "operational", "execution", "resilience"],
    dimension: "RECALL",
    translationEs: "Para acortar la brecha entre nuestra visión y nuestra ejecución operativa, debemos priorizar la resiliencia por encima de todo.",
    hint: "Imitate the rise in pitch before the comma and the strong rhythmic emphasis on 'RESILIENCE'.",
  },
];
